### ISSUE TITLE
Possible to add a parser option?

### ISSUE THREAD

**Issue by corysimmons** [AtomLinter/linter-stylelint#81] opened 2016-02-08 19:59 UTC
I'm not sure if this is a stylelint problem or a linter-stylelint problem, but is it possible to add an option for something like Sass?

The problem comes because I'll frequently have a style with just a single mixin in it, and the `at-rule-empty-line-before` thing interprets the mixin as an @ rule.

![image](https://cloud.githubusercontent.com/assets/224636/12897269/703c19f6-ce74-11e5-882a-c44730c18286.png)

This means I end up with these all over the place:

```scss
.foo {

  @include button(red);
}
```

**Comment by davidtheclark** [comment] 2016-02-09 14:11
Duplicate of https://github.com/stylelint/stylelint/issues/713. It's an issue with stylelint, not this plugin, so can be closed.

**Closed** 2016-02-09 15:41 UTC

**Comment by apexskier** [comment] 2016-07-13 19:13
The duplicate ticket has been closed without any resolution. stylelint itself is intended for css, but this atom package runs on sass as well. Can this be reopened?

**Comment by Arcanemagus** [comment] 2016-07-13 23:03
@apexskier This package [sets the appropriate flag](https://github.com/AtomLinter/linter-stylelint/blob/v2.17.0/lib/index.js#L202-L209) to tell `stylelint` that a file is to be processed with the Sass preprocessor.

If you are having issues with that not being set properly, please file a new issue here. However if you are seeing issues with the results, and `stylelint ./foo.scss --syntax scss` shows the **same** results, then the issue is with `stylelint`, or an incompatibility between one of the rules you have enabled and the 3rd party syntax. If that is the case, you should file an issue on the `stylelint` repo to track that down.

**Comment by apexskier** [comment] 2016-07-13 23:27
You're totally right. I think my problem was that I was forcing use of a different stylelint config and things were screwing up. It's behaving correctly now.

**Comment by contra** [comment] 2019-05-02 17:07
This seems like it was fixed for scss extensions but not sass extensions (https://github.com/AtomLinter/linter-stylelint/blob/master/lib/index.js#L143-L150)

Is that right? If so I can send a PR to fix.
