### ISSUE TITLE
linter-stylelint breaks when adding plugins to .stylelintrc

### ISSUE THREAD

**Issue by squidfunk** [AtomLinter/linter-stylelint#297] opened 2016-10-19 13:44 UTC
The stylelint plugin works as expected, until one adds plugins to the `.stylelintrc`:

``` json
{
  "extends": "stylelint-config-standard",
  "plugins": [
    "stylelint-declaration-block-order",
    "stylelint-scss"
  ]
}
```

When saving a file (with "linting on save" activated), the following error message is shown and stylelint is not running:

![bildschirmfoto 2016-10-19 um 15 40 43](https://cloud.githubusercontent.com/assets/932156/19521054/a1737eea-9612-11e6-9fd1-8ec537057579.png)

> **Unable to parse stylelint configuration**
> ---
> Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

It seems, that it does not matter which plugins are added. When the plugin array is left empty, everything works as expected. ESLint seems to have had the same problem:
https://github.com/AtomLinter/linter-eslint/issues/177

**Versions**:

* linter-stylelint: 3.4.1
* linter: 1.11.18
* atom: 1.10.2

**Comment by Arcanemagus** [comment] 2016-10-19 16:18
`stylelint-scss` is the culprit here, it brings in its own version of `stylelint`, which depends on `table`, which had some issues with using `eval`. If you re-install your plugins it should bring in the latest version of `table` as a sub-dependency, which is able to run within Atom.

Closing this as a duplicate of #269.

**Closed by Arcanemagus** 2016-10-19 16:18 UTC

**Comment by squidfunk** [comment] 2016-11-03 17:35
Can you please elaborate what has to be done? I'm still experiencing the issue. It doesn't only happen with `stylelint-scss`, but also with any other plugin.

**Comment by Arcanemagus** [comment] 2016-11-03 17:40
@squidfunk The sub-sub-dependency that was breaking this has been fixed by now, you need to update to the current version of this package, **and** update the sub-dependencies in your project where the plugins are installed. The simplest way to do this is to just remove the `node_modules` folder and run `npm install` again.

**Comment by squidfunk** [comment] 2016-11-03 17:41
Thanks, will give it a try.

**Comment by mattclough1** [comment] 2016-11-09 18:39
@squidfunk any luck with that?

**Comment by squidfunk** [comment] 2016-11-10 08:59
Unfortunately not. I upgaded `linter-stylelint` to the latest version, I killed the `node_modules` folder, did a clean install, but I keep getting the error message.

**Comment by mattclough1** [comment] 2016-11-10 14:26
I finally did resolve this as prescribed. Turns out I just hadn't actually updated the `table` dependency. Updating to `table@^3.8.3` fixed it. Make sure you don't have a lockfile preventing `table` from updating.

**Comment by squidfunk** [comment] 2016-11-10 14:28
Maybe I just don't see it. Did you add table as a dependency manually?

**Comment by mattclough1** [comment] 2016-11-10 14:44
I was trying to use a plugin that required `stylelint` which itself requires `table`. Check your `node_modules` and see if it's installed, even if it's not in your `package.json`

**Comment by squidfunk** [comment] 2016-11-10 14:59
Okay, seems to work now. I killed all stylelint packages, installed table manually, and then reinstalled stylelint.

``` json
...
  "stylelint": "^7.4.2",
  "stylelint-config-standard": "^13.0.2",
  "stylelint-scss": "^1.3.4",
  "table": "^3.8.3",
...
```

Thanks!
