### ISSUE TITLE
Fails when extending configs that extend other configs and include plugins

### ISSUE THREAD

**Issue by davidtheclark** [AtomLinter/linter-stylelint#104] opened 2016-02-24 15:57 UTC
Weird one here. It *does* work with the stylelint CLI, but seems to fail here.

configA:

```json
{ "extends": [ "./build-lib/configB.json" ] }
```

build-lib/configB:

```json
{ 
  "extends": [ "stylelint-config-standard" ],
  "plugins": [ "stylelint-selector-bem-pattern" ],
  "rules": {..} 
}
```

If I run this, I get the error `Cannot find module 'stylelint-selector-bem-pattern'`.

If I remove configB's `extends` (keeping the `plugins`), it works.

If I remove configB's `plugins` (keeping the `extends`), it works.

If I remove configB's `extends` and change configA so that it `"extends": [ "stylelint-config-standard", "./build-lib/configB.json" ]`, it works.

Any ideas?

**Comment by Arcanemagus** [comment] 2016-03-11 18:04
Attempting to reproduce this now.

**Comment by Arcanemagus** [comment] 2016-03-12 07:32
Okay, looking into this for real this time :stuck_out_tongue:.

**Comment by Arcanemagus** [comment] 2016-03-12 08:12
Do you maybe have that package installed globally? I am seeing the same issue from the CLI.

**Comment by Arcanemagus** [comment] 2016-03-12 09:04
It looks like what is going on is that [this function](https://github.com/stylelint/stylelint/blob/5.0.0/src/buildConfig.js#L58) properly replaces the plugin name with the full path to the plugin, but in the process of merging everything together this gets dropped and the original value of just the plugin name is used instead. I _think_ that this is due to `configWithAbsolutePlugins` not being used through the whole function, which it seems was the original intent. Modifying my local copy now to test this theory.

**Comment by Arcanemagus** [comment] 2016-03-12 09:21
Yep, looks like that fixes it, I'll put a PR up to `stylelint`.

**Comment by Arcanemagus** [comment] 2016-03-12 10:06
Marking as closed since this is a `stylelint` issue, PR is up there that fixes this :wink:.

**Closed by Arcanemagus** 2016-03-12 10:06 UTC
Labels: External
