### ISSUE TITLE
Undefined rule: selector-attribute-quotes

### ISSUE THREAD

**Issue by abaracedo** [AtomLinter/linter-stylelint#227] opened 2016-07-07 18:57 UTC
It seems this rule is not yet added in the linter and throws the error

**Comment by Arcanemagus** [comment] 2016-07-07 18:58
Duplicate of #226. `stylelint@6.9.0` is the first release to include that rule, and it's only 2 hours old 😛.

**Closed by Arcanemagus** 2016-07-07 18:58 UTC
Labels: duplicate

**Comment by Arcanemagus** [comment] 2016-07-07 23:50
v2.17.0 is published including this version, enjoy 😉.

**Comment by abaracedo** [comment] 2016-07-09 07:42
Thanks! Good job :+1:
