### ISSUE TITLE
Unable to use plugins

### ISSUE THREAD

**Issue by leepfrog** [AtomLinter/linter-stylelint#276] opened 2016-09-22 01:57 UTC
Whenever I use a plugin on my .stylelintrc, atom throws the following error:

```
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
```

It doesn't seem to matter what the plugin is (I've tried https://github.com/timothyneiljohnson/stylelint-selector-no-mergeable and https://github.com/sh-waqar/stylelint-declaration-use-variable) plugins.

I'm using these plugins in my node project -- they exist in my package.json.  I've installed them, and they exist in node_modules.  npm test works correctly.

**Comment by racse1** [comment] 2016-09-23 13:45
Hi all, I've got same issue when I was trying to set up my project using [stylelint-config-primer](https://github.com/primer/stylelint-config-primer).

Node.js: v6.2.0.
npm: v3.8.9.
Atom: v1.10.2.
linter: v1.11.16.
linter-stylelint: v3.3.1.

**Comment by ErikFontanel** [comment] 2016-09-23 19:39
Same here with the stylelint 3.3.1

**Comment by ascariandrea** [comment] 2016-09-26 15:51
Give a look at https://github.com/AtomLinter/linter-eslint/pull/179

**Comment by FrancescoCioria** [comment] 2016-09-28 13:32
might be a duplicate of #269 
The outcome of 269 was this issue on stylelint: https://github.com/stylelint/stylelint/issues/1912

**Comment by FrancescoCioria** [comment] 2016-09-28 13:42
possible workaround for now (as suggested at the end of #269):
1) add `table@3.7.8` to your devDependencies
2) fresh install of `node_modules`

```
npm i --save-dev table@3.7.8
```
```
rm -rf node_modules && npm i
```

**Comment by Arcanemagus** [comment] 2016-10-12 21:06
Marking this as a duplicate of #269.

**Closed by Arcanemagus** 2016-10-12 21:06 UTC
