### ISSUE TITLE
Error: Column start (1268) greater than line length (25)

### ISSUE THREAD

**Issue by corysimmons** [AtomLinter/linter-stylelint#79] opened 2016-02-08 02:26 UTC
![image](https://cloud.githubusercontent.com/assets/224636/12877393/a5513390-cde0-11e5-9c8e-74b893f36808.png)

Happens the second I remove a quote (happens all the time for other stuff too but this time I caught it).

```css
/**
 * Multi-line comment
 */

.selector-1,
.selector-2,
.selector-3[type=text"] {
  background: linear-gradient(#fff, rgba(0, 0, 0, 0.8));
  box-sizing: border-box;
  display: block;
  color: #333;
}

.selector-a,
.selector-b {
  padding: 10px !important;
  top: calc(calc(1em * 2) / 3);
}

.selector-x { width: 10%; }
.selector-y { width: 20%; }
.selector-z { width: 30%; }

/* Single-line comment */

@media (min-width >= 60em) {
  .selector {
    /* Flush to parent comment */
    transform: translate(1, 1) scale(3);
  }
}

@media (min-orientation: portrait), projection and (color) {
  .selector-i + .selector-ii {
    background: color(rgb(0, 0, 0) lightness(50%));
    font-family: helvetica, arial, sans-serif;
  }
}

/* Flush single line comment */
@media screen and (min-device-pixel-ratio: 2),
  screen and (min-resolution: 192dpi),
  screen and (min-resolution: 2dppx) {

  .selector {
    background-image:
      repeating-linear-gradient(
        -45deg,
        transparent,
        #fff 25px,
        rgba(255, 255, 255, 1) 50px
      );
    margin: 10px;
    margin-bottom: 5px;
    box-shadow:
      0 1px 1px #000,
      0 1px 0 #fff,
      2px 2px 1px 1px #ccc inset;
    height: 10rem;
  }

  /* Flush nested single line comment */
  .selector::after {
    content: "→";
    background-image: url("x.svg");
  }
}
```

```js
// stylelint.config.js
module.exports = {
  'plugins': [
    'stylelint-statement-max-nesting-depth'
  ],
  'rules': {
    // Plugins
    'statement-max-nesting-depth': [3, {
      countAtRules: false,
      countedNestedAtRules: false
    }],

    // String
    'string-quotes': 'single',

    // Color
    'color-hex-case': 'lower',
    'color-hex-length': 'short',
    'color-no-invalid-hex': true,
    'color-no-named': true,

    // Number
    'number-leading-zero': 'always',
    'number-max-precision': 3,
    'number-no-trailing-zeros': true,
    'number-zero-length-no-unit': true,

    // Function
    'function-calc-no-unspaced-operator': true,
    'function-comma-space-after': 'always',
    'function-comma-space-before': 'never',
    'function-linear-gradient-no-nonstandard-direction': true,

    // Value list
    'value-list-comma-space-after': 'always',
    'value-list-comma-space-before': 'never',

    // Unit
    'unit-blacklist': ['em', 'rem'], // Disallow these because PostCSS adds them

    // Declaration
    'declaration-bang-space-after': 'never',
    'declaration-bang-space-before': 'always',
    'declaration-colon-space-after': 'always',
    'declaration-colon-space-before': 'never',
    'declaration-no-important': true, // Ask DG if this is causing you problems

    // Declaration block
    'declaration-block-semicolon-newline-after': 'always-multi-line',
    'declaration-block-semicolon-space-after': 'always-single-line',

    // Block
    'block-closing-brace-newline-after': 'always',
    'block-closing-brace-newline-before': 'always-multi-line',
    'block-closing-brace-space-before': 'always-single-line',
    'block-no-empty': true,
    'block-opening-brace-newline-after': 'always-multi-line',
    'block-opening-brace-space-after': 'always-single-line',
    'block-opening-brace-space-before': 'always',

    // Selector
    'selector-combinator-space-after': 'always',
    'selector-combinator-space-before': 'always',
    'selector-no-id': true,
    'selector-no-type': true, // Ask DG if this is causing you problems
    'selector-no-universal': true,
    'selector-no-vendor-prefix': true,
    'selector-pseudo-element-colon-notation': 'double',

    // Selector list
    'selector-list-comma-space-after': 'always-single-line',
    'selector-list-comma-space-before': 'never',

    // Rules
    'rule-nested-empty-line-before': ['always', {
      except: ['first-nested'],
      ignore: ['after-comment']
    }],
    'rule-no-duplicate-properties': true,
    'rule-no-shorthand-property-overrides': true,
    'rule-non-nested-empty-line-before': ['always-multi-line', {
      ignore: ['after-comment']
    }],
    'rule-properties-order': [
      {
        emptyLineBefore: true,
        properties: [
          'content'
        ]
      },
      {
        emptyLineBefore: true,
        properties: [
          'position',
          'top',
          'right',
          'bottom',
          'left',
          'z-index'
        ]
      },
      {
        emptyLineBefore: true,
        properties: [
          'align-content',
          'align-items',
          'align-self',
          'flex',
          'flex-basis',
          'flex-direction',
          'flex-flow',
          'flex-grow',
          'flex-shrink',
          'flex-wrap',
          'justify-content',
          'order'
        ]
      },
      {
        emptyLineBefore: true,
        properties: [
          'display',
          'float',
          'height',
          'margin',
          'margin-top',
          'margin-right',
          'margin-bottom',
          'margin-left',
          'max-height',
          'max-width',
          'min-height',
          'min-width',
          'padding',
          'padding-top',
          'padding-right',
          'padding-bottom',
          'padding-left',
          'table-layout',
          'width'
        ]
      },
      {
        emptyLineBefore: true,
        properties: [
          'font-family',
          'font-size',
          'font-style',
          'font-weight',
          'letter-spacing',
          'line-height',
          'text-align',
          'text-decoration',
          'text-overflow'
        ]
      },
      {
        emptyLineBefore: true,
        properties: [
          'appearance',
          'background',
          'background-attachment',
          'background-blend-mode',
          'background-color',
          'background-image',
          'background-position',
          'background-repeat',
          'background-size',
          'border',
          'border-top',
          'border-right',
          'border-bottom',
          'border-left',
          'border-radius',
          'border-top-left-radius',
          'border-top-right-radius',
          'border-bottom-right-radius',
          'border-bottom-left-radius',
          'box-shadow',
          'color',
          'cursor',
          'mix-blend-mode',
          'opacity',
          'overflow',
          'overflow-x',
          'overflow-y',
          'visibility'
        ]
      },
      {
        emptyLineBefore: true,
        properties: [
          'animation',
          'animation-delay',
          'animation-direction',
          'animation-duration',
          'animation-fill-mode',
          'animation-iteration-count',
          'animation-name',
          'animation-play-state',
          'animation-timing-function',
          'transform',
          'transition'
        ]
      }
    ],
    'rule-trailing-semicolon': 'always',

    // Media
    'media-feature-colon-space-after': 'always',
    'media-feature-colon-space-before': 'never',
    'media-feature-name-no-vendor-prefix': true,
    'media-feature-range-operator-space-after': 'always',
    'media-feature-range-operator-space-before': 'always',

    // Custom media
    'custom-media-pattern': 'xs|sm|md|lg|xlg|xxlg.+/',

    // Media query
    'media-query-parentheses-space-inside': 'never',

    // At rule
    'at-rule-empty-line-before': ['always', {
      except: ['blockless-group', 'first-nested'],
      ignore: ['after-comment']
    }],
    'at-rule-no-vendor-prefix': true,

    // Comment
    'comment-whitespace-inside': 'always',

    // General
    'indentation': 2,
    'no-eol-whitespace': true,
    'no-missing-eof-newline': true
  }
}
```

Originally ran into this and opened an issue here: https://github.com/atom-community/linter/issues/1069

Then I went to stylelint to open an issue: https://github.com/stylelint/stylelint/issues/688 and was pointed here.

@Arcanemagus @davidtheclark can we get to the bottom of this? It happens so frequently it makes linter-stylelint unusable.

**Comment by corysimmons** [comment] 2016-02-08 04:30
Another one just happened when I entered a newline.

![image](https://cloud.githubusercontent.com/assets/224636/12878431/c51492fa-cdf2-11e5-870e-d8237b10dec4.png)

**Comment by davidtheclark** [comment] 2016-02-08 13:29
@corysimmons Unless you can reproduce inaccurate positions *outside of Atom*, this is definitely an issue with linter-stylelint and should be address over in that repo. We have plenty of unit tests here validating that line/column positions point where they should.

@Arcanemagus I wonder if this is just a timing issue in the plugin, and adding a short delay somewhere would fix it?

**Comment by corysimmons** [comment] 2016-02-08 17:03
This happens when I load Foundation's config file with WordPress stylelint enabled:

![image](https://cloud.githubusercontent.com/assets/224636/12892833/f5b4fd32-ce5b-11e5-86c3-0467085ad793.png)

**Comment by davidtheclark** [comment] 2016-02-09 14:20
I suspect that this is a duplicate of #82 -- the same postcss-scss positioning problem.

**Comment by corysimmons** [comment] 2016-02-09 15:44
Not sure what it is. I've never ran into this error with CLI and I run into it every few minutes in Atom.

**Comment by Arcanemagus** [comment] 2016-02-09 19:11
@corysimmons This linter runs on the code as you are typing it, so it's far more likely to run into bizarre situations that the `stylelint` linter (or a dependency) doesn't handle properly. When you see something like this it would be helpful if you immediately save the file and try from the command line to verify whether the cause is this plugin or `stylelint` itself.

@davidtheclark the delay between when a user stops typing and when lints are triggered can be configured, I think the default is only 200ms, personally I've bumped it up to 1500 ms myself.

I'm going to try to reproduce this now with the code you posted above.

**Comment by corysimmons** [comment] 2016-02-09 19:47
> When you see something like this it would be helpful if you immediately save the file and try from the command line to verify whether the cause is this plugin or stylelint itself.

Gotcha, will do in the future but I've already left Atom so I doubt I'll be back anytime soon.

**Comment by Arcanemagus** [comment] 2016-02-09 21:52
Looks like this is due to `stylelint` throwing a `CssSyntaxError` and `linter-stylelint` parsing that as output.

**Comment by Arcanemagus** [comment] 2016-02-09 22:03
Filed an issue over on the `stylelint` repo with a minimal test case, all yours @davidtheclark :wink:.

**Closed by Arcanemagus** 2016-02-09 22:03 UTC

**Comment by MattDiMu** [comment] 2016-04-18 09:42
I'm experiencing the same issue with about 70% of my .scss-files, so I'm basically unable to use this (actually great) plugin. Using Win7 with the latest packages of Atom@1.7.1, linter@1.11.4, linter-stylelint@2.3.0.

One example-file, causing this error:
```
Error: Column start (2) greater than line length (1)
Error: Column start (2) greater than line length (1)
    at rangeFromLineNumber (C:\Users\xxx\.atom\packages\linter-eslint\node_modules\atom-linter\lib\index.js:194:11)
    at createRange (C:/Users/xxx/.atom/packages/linter-stylelint/lib/index.js:35:10)
    at C:/Users/xxx/.atom/packages/linter-stylelint/lib/index.js:74:14
    at Array.map (native)
    at stylelint.lint.then.error.type (C:/Users/xxx/.atom/packages/linter-stylelint/lib/index.js:70:38)

```
with the following scss-file:
```
form {
}


input, button, textarea {
  border: 1px solid $color-form-element-border;
}
```

and the following config:
```
{
  "extends": "stylelint-config-standard",
  "rules": {
    "number-leading-zero": null,
  }
}
```

When running in the command line, it actually works:
```
_form.scss
1:6     Unexpected empty block (block-no-empty)
2:3     Unexpected empty line (max-empty-lines)
5:6     Expected newline after "," (selector-list-comma-newline-after)
5:14    Expected newline after "," (selector-list-comma-newline-after)

```

**Comment by Arcanemagus** [comment] 2016-04-18 17:43
@MattDiMu As this error is generally a rather unique situation can you please file a new issue so we can discuss this further?
