### ISSUE TITLE
"Unable to run stylelint: this.spacesFromStart is not a function" when writing out a property.

### ISSUE THREAD

**Issue by joeyred** [AtomLinter/linter-stylelint#321] opened 2017-02-17 22:05 UTC
# The Problem

This error keeps getting thrown, usually when I'm adding a property above a nested rule working in scss. The error ends up popping up with Atom's notification system for errors. While this doesn't crash anything, and the listing still operates, it gets annoying having the errors pile up until i can finally finish writing the rule, and then having to close out the notifications.

# Example

## Code
```scss
&.active {
    position: fixed;
    top:

    .tab {
      h2 {
        flex: auto;
      }
   }
}
```
## Screenshots
![screen shot 2017-02-17 at 5 03 47 pm](https://cloud.githubusercontent.com/assets/12838699/23084991/1d2ee914-f533-11e6-82f7-4f5e1b95d11a.png)

![screen shot 2017-02-17 at 5 53 05 pm](https://cloud.githubusercontent.com/assets/12838699/23086271/00da751a-f53a-11e6-875d-7f1ed9ffe069.png)

This is what it looks like when this error pops up.

**Comment by Arcanemagus** [comment] 2017-02-22 00:56
I'm trying to reproduce this with no luck so far, however I did discover and file https://github.com/stylelint/stylelint/issues/2374 while attempting to reproduce this.

**Comment by Arcanemagus** [comment] 2017-02-22 01:04
Okay, I've tried everything I can think of to reproduce with the code you have posted there, but I can't replicate the error. I notice that the files are in an unsaved state in your screenshot, are you able to get a file that shows that error every time you save it?

**Comment by joeyred** [comment] 2017-02-22 03:51
The error never happens on save. It happens as I am typing, and it is actively linting. This happens to me as I work. I write in a new property, type in the colon, and then every character after that, until I finally use a semi-colon, throws this error.

![stylelint-error-example](https://cloud.githubusercontent.com/assets/12838699/23196503/0b25f76e-f888-11e6-9d0d-ab4599029a3b.gif)

**Comment by Arcanemagus** [comment] 2017-02-22 04:26
Can you post your stylelint config? Obviously whatever is breaking isn't used in `stylelint-config-standard`.

**Comment by evilebottnawi** [comment] 2017-02-23 14:39
@Arcanemagus already fixed https://github.com/stylelint/stylelint/issues/2374#issuecomment-282003260

**Comment by Arcanemagus** [comment] 2017-02-23 17:14
@evilebottnawi It's not "already fixed" from the perspective of `stylelint` though 😛.

**Comment by kellyrmilligan** [comment] 2017-02-23 17:50
found this as well. v 3.8.1 on atom, when I type `$color-blue:` when I type the colon and hit space, it throws that error.

**Comment by kellyrmilligan** [comment] 2017-02-23 17:51
on an .scss file.

**Comment by evilebottnawi** [comment] 2017-02-23 17:52
@kellyrmilligan try to remove `node_modules` and install all again

**Comment by kellyrmilligan** [comment] 2017-02-23 17:53
from where? @evilebottnawi

**Comment by evilebottnawi** [comment] 2017-02-23 17:55
@kellyrmilligan from `linter-stylelint` package in atom, i think :smile:

**Comment by Arcanemagus** [comment] 2017-02-23 17:55
@kellyrmilligan You can accomplish that by uninstalling `linter-stylelint` and re-installing it.

**Comment by kellyrmilligan** [comment] 2017-02-23 17:55
will try right now

**Comment by kellyrmilligan** [comment] 2017-02-23 17:59
did that, same issue.

**Comment by Arcanemagus** [comment] 2017-02-23 18:05
If you have Node.js install can you run `npm list postcss-scss` and report the version?

**Comment by kellyrmilligan** [comment] 2017-02-23 18:07
└─┬ stylelint@7.8.0
  └── postcss-scss@0.4.0

**Comment by Arcanemagus** [comment] 2017-02-23 18:09
Can you update your `linter-stylelint` package? It looks like you are still on v3.8.0 or v3.8.1.

**Comment by kellyrmilligan** [comment] 2017-02-23 18:12
atom seems to think that's the latest?

**Comment by kellyrmilligan** [comment] 2017-02-23 18:15
confirmed it's fixed with 3.9.0

**Comment by joeyred** [comment] 2017-02-23 22:13
Since updating to 3.9.0 today, the issue seems to be solved now.

**Comment by Arcanemagus** [comment] 2017-02-23 22:47
I'm marking this as closed since it seems the fixed version of `postcss-scss` is allowed in the current version of `stylelint`. The issue I discovered related to an incorrect position being reported is a separate bug that has been reported to the proper place.

Thanks for taking the time to report this everyone!

**Closed by Arcanemagus** 2017-02-23 22:47 UTC
Labels: External
