### ISSUE TITLE
Support stylelint 7.8.0

### ISSUE THREAD

**Issue by tonygentilcore** [AtomLinter/linter-stylelint#314] opened 2017-02-02 16:10 UTC
Stylelint 7.8.0 was just released. This package reports:

```
Unable to parse stylelint configuration
Undefined rule rule-empty-line-before
```

<img width="475" alt="screen shot 2017-02-02 at 8 09 27 am" src="https://cloud.githubusercontent.com/assets/1731736/22557316/11bbd6e8-e91f-11e6-8620-92ae8b53be8f.png">

**Comment by Arcanemagus** [comment] 2017-02-03 19:01
Closing as a duplicate of #312, Greenkeeper beat you to it by 3 hours, I just hadn't had time to look into it 😛.

**Closed by Arcanemagus** 2017-02-03 19:01 UTC

**Comment by adnasa** [comment] 2017-02-11 23:38
thanks for this @Arcanemagus !
