### ISSUE TITLE
Can't get browserlist in package.json or browserlist file to be recognised when using stylelint-no-unsupported-browser-features

### ISSUE THREAD

**Issue by benlane** [AtomLinter/linter-stylelint#344] opened 2017-06-19 15:13 UTC
The only way I seem to be able to get the browserlist to be recognised is by setting it in the configuration for the plugin directly using the browsers option rather than having it in the package.json or a browserlist file in the root of the project.

I am using atom and the plugin and stylelint versions should be the latest as I only installed them on the project today.

Is there an example of this working with the package.json or browserlist file configuration.

my stylelint config is as follows

```json
{
  "plugins": ["stylelint-no-unsupported-browser-features"],
  "rules": {
    "plugin/no-unsupported-browser-features": [true, {
      "severity": "warning",
      "ignore": ['rem']
    }]
  }
}
```

I raised this as an issue on that plugin and the creator mentioned it may be an issue with this linter https://github.com/ismay/stylelint-no-unsupported-browser-features/issues/27

**Comment by pixelass** [comment] 2017-06-22 19:03
I have the same issue.

**Comment by ismay** [comment] 2017-07-08 10:08
> I have the same issue. It works in VSCode and SublimeText

Same issue with atom on mac here as well. Exact same project works for me in neovim.

**Comment by Arcanemagus** [comment] 2017-07-10 17:43
How would this get reproduced? I'm guessing this is an issue with `stylelint` or `stylelint-no-unsupported-browser-features` improperly caching paths between lint runs as we only ever use one `stylelint` instance per Atom window which isn't a normal use case, but should still be supported.

(Most uses of `stylelint` load it up, run a lint job, and then close it again so the next run is a fresh start, hiding cross-run issues like this.)

**Comment by Arcanemagus** [comment] 2017-08-21 23:22
Still waiting on steps to reproduce this to try to diagnose where the issue is.

**Comment by pixelass** [comment] 2017-08-22 17:06
I don't use Atom. I experienced this when setting up a dev environment for a project at work. Sadly I can't help here.

**Comment by MSBuV** [comment] 2017-08-23 10:56
The new update fixed the issue for me on Windows 10. No more error-message and correct linter-hints on the setting "Use standard".
Not sure if it is related, but I had warning messages for no empty lines between selectors at first, one minute later they were gone. Other warning messages are working.
All with a standard css-file.
Also, https://stylelint.io/user-guide/rules/CssSyntaxError gives a 404 error, clicking on the icon in the stylelint warning message.

**Comment by Arcanemagus** [comment] 2017-08-23 18:43
Okay, after a ton of digging through the sources of all the related modules, it turns out this is a bug in `doiuse`. They forgot to handle a function parameter which defines the file being linted. In a lot of cases this wouldn't matter since the default value used where it is needed is the cwd... but the cwd when run through the Node API is slightly different than if used on the CLI, causing the problem here.

As to why this works in VSCode and Sublime text? I'm guessing they are just wrapping the CLI instead
 of actually using the code 😛.

I'll be submitting a PR fixing this in `doiuse`.

----

@MSBuV You listed _several_ different things in that post, none of which seemed related to this issue? If you are having a problem please file **separate** issues for each problem you are having.

**Comment by Arcanemagus** [comment] 2017-08-24 16:02
Fix merged in, the next release of `doiuse` should work for you guys.

**Closed by Arcanemagus** 2017-08-24 16:02 UTC
Labels: Bug, External
