### ISSUE TITLE
Stylelint bin is dictated by the plugin and is not configurable

### ISSUE THREAD

**Issue by kmiyashiro** [AtomLinter/linter-stylelint#361] opened 2017-07-24 17:51 UTC
An option to use the local `./node_modules/.bin/stylelint` would be super helpful. Currently, the plugin forces the user to use the same version of stylelint that the plugin uses. This is very problematic for many reasons:

* With the latest major upgrade to 8.0, many rules broke
* Different projects may not be on the same version of stylelint
* The version of your linter should not be determined by a plugin, it should either use the local global bin or the local bin

**Comment by Arcanemagus** [comment] 2017-07-24 18:04
Duplicate of #51.

**Closed by Arcanemagus** 2017-07-24 18:04 UTC
