### ISSUE TITLE
Error in Atom: Unable to run stylelint

### ISSUE THREAD

**Issue by Bubbi** [AtomLinter/linter-stylelint#281] opened 2016-10-04 08:10 UTC
Great plugin, i've been using it a lot!

I have previously used it on a Win7 machine, but I have just installed Atom on a new Ubuntu 16.04 and installed linter-stylelint and it reports the following error, in a red box in the upper right corner:

**Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".**

I saw that a previous version had an identical error, which was fixed, i guess(?). https://github.com/AtomLinter/linter-stylelint/issues/90

Anybody else getting this error and anybody know how to fix it, or do we need a new version of linter-stylelint?

I don't know much about the "required" dependencies and such, but I have the following devDependencies.. Maybe something here can give a hint to as what I have done wrong or what can maybe fix it...:

```
  "devDependencies": {
    "eslint": "^3.2.2",
    "node-sass": "^3.8.0",
    "stylefmt": "^4.3.0",
    "stylelint": "^7.1.0",
    "stylelint-scss": "^1.3.4"
  }
```

**Comment by Arcanemagus** [comment] 2016-10-04 16:23
It's quite likely this is a duplicate of #269, possibly being triggered through running a plugin (#276). It's a mess either way. The original issue on Ajv was closed, haven't had time to look into whether it actually fixes things though.

**Comment by Arcanemagus** [comment] 2016-10-12 20:02
Looked back over your dependency list, this is definitely a duplicate of #269 according to https://github.com/AtomLinter/linter-stylelint/issues/269#issuecomment-248410548.

**Closed by Arcanemagus** 2016-10-12 20:02 UTC
