### ISSUE TITLE
Strang errors during writing SugarSS

### ISSUE THREAD

**Issue by ai** [AtomLinter/linter-stylelint#260] opened 2016-09-06 06:21 UTC
When I write selector, Atom show plugin error (not linter error)

![c3zr5wp](https://cloud.githubusercontent.com/assets/19343/18263520/ecea621c-744d-11e6-9b63-a342e8d797ad.png)

**Comment by Arcanemagus** [comment] 2016-09-06 18:28
Can you provide the relevant configuration file? This is most likely due to a mapping issue in the SCSS -> CSS -> SCSS translations that are performed internally while Stylelint is running.

Atom is just exposing the error since Stylelint is saying there is something at column 40 on a line with only 38 characters.

**Comment by Arcanemagus** [comment] 2016-09-06 18:47
In fact, as the error that _is_ showing is relating to white space at the end of a line, can you put that raw file up as well?

**Comment by Arcanemagus** [comment] 2016-09-06 18:51
Nevermind, looks like `stylelint-config-standard` is able to reproduce it with what is visually visible there. Next time uploading the raw files would save a lot of hand transcribing 😉.

**Comment by Arcanemagus** [comment] 2016-09-06 19:02
I'm able to reproduce this on the CLI:

![image](https://cloud.githubusercontent.com/assets/427137/18286909/b9313654-7429-11e6-8a28-ef17e5b37dcb.png)

Note the error being reported on column 41 (1-indexed) on a line with only 39 columns.

I used the following files: [linter-stylelint_GH260.zip](https://github.com/AtomLinter/linter-stylelint/files/457552/linter-stylelint_GH260.zip)

Do you want to file this over on `stylelint`? Or do you want me to?

**Comment by ai** [comment] 2016-09-06 22:47
@Arcanemagus if it is Stylelint error, why it was shown in plugin error popup, not just in regular line highlight as any other linter errors?

**Comment by Arcanemagus** [comment] 2016-09-06 23:14
Because it's a bug in how Stylelint is working, not an error `throw`n from inside Stylelint. As far as Stylelint is concerned it is quite happy reporting an error at column 41 because that's what the rule told it to report. It makes no checks as to whether that line actually _has_ 41 columns, while the `rangeFromLineNumber` function in `atom-linter` that actually generates the range to use _does_ check that, and `throw`s an error when the requested column is outside the possible values.

**Comment by ai** [comment] 2016-09-07 03:20
So, how I could fix it? Right now I could not use `linter-stylelint` because this errors block code.

Should I open issue in `atom-linter` or `stylelint`? And what I should report there?

Sorry, I really still don’t understand what is this error about :D

**Comment by Arcanemagus** [comment] 2016-09-07 17:35
I'll file it over on `stylelint` 😉.

**Comment by ai** [comment] 2016-09-08 02:52
@Arcanemagus thanks :)

**Comment by Arcanemagus** [comment] 2016-09-20 21:38
Marking this as closed, anyone coming across this issue should follow https://github.com/stylelint/stylelint/issues/1889 for updates on when this will be fixed.

**Closed by Arcanemagus** 2016-09-20 21:38 UTC
Labels: External
