### ISSUE TITLE
Make file extensions to parse configurable

### ISSUE THREAD

**Issue by jaydenseric** [AtomLinter/linter-stylelint#306] opened 2017-01-09 08:09 UTC
It would be good to get linter-stylelint to work on .js files for [stylelint-processor-styled-components](https://github.com/styled-components/stylelint-processor-styled-components) users.

Can a simple comma separated list of additional file extensions to parse be added to the settings?

**Comment by Arcanemagus** [comment] 2017-01-09 08:46
Marking as a duplicate of #235, I might have time to re-implement that this coming week...

**Closed by Arcanemagus** 2017-01-09 08:46 UTC
